Sprint 7 impl
Dmitry-Nikishov/MovieQuiz-ios pull request #6
Opened 2023-01-30 13:46 UTC by Dmitry-Nikishov

2023-01-31 09:50 UTC, IBDesignable requested changes

2023-01-31 09:50 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    }()
мне не нравится такая инициализация сервиса. Так как хоть и во вне ты отдаешь протокольный тип, но реализация презентера все еще зависит от конкретной реализации. Если бы тестировал работу связанную со статистикой, то у тебя возникли бы сложности с моком этого сервиса. 
На данном этапе не хватает знаний о том как реализовывать DI и в этом приложении он избыточен. Но  инджекцию сервисов стоит переделать через инициализатор, создавая все зависимости во вью контроллере. 

Можно подробнее погрузиться в DI например [с этой статьи](https://habr.com/ru/company/tinkoff/blog/546360/), если будет сложно – по ключевым словам поискать все что не понятно

2023-01-31 09:50 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +
давай держать порядок в классе: в одном месте, сверху - все свойства, затем все функции

2023-01-31 19:35 UTC, Dmitry-Nikishov commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    }()
Спасибо за ссылку по DI - статью изучил, вопросов нет, все понятно. С замечанием согласен, поправил

2023-01-31 19:35 UTC, Dmitry-Nikishov commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +
да, упустил это поле, мой косяк

2023-02-01 17:22 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +        statisticsService = ss
ловкое решение!)) хотя все таки обще принято `self.viewController = viewController`

2023-02-02 20:16 UTC, merged